### PR TITLE
Fix syntax in template

### PR DESCRIPTION
**Pull request by SubJunk**
This change is [Reviewable](https://reviewable.io/reviews/digitalmediaserver/crowdin-maven-plugin/3)

### CODE REVIEW

**Comment by Nadahar** [comment]
@SubJunk Thanks :+1:

**Comment by Nadahar** [comment]
@SubJunk If you're looking at this because the "old plugin" doesn't work anymore because crowdin has shut down their "old" API, it won't help. I haven't found the time to implement their "new" API yet.

**Comment by SubJunk** [comment]
This plugin is thankfully still working well despite Crowdin saying they would end support months ago, I just had a drive die and hadn't backed up my maven settings

**Comment by Nadahar** [comment]
Ah, nice. I have no idea why, but it’s good to hear :+1:

**Comment by Nadahar** [comment]
@SubJunk I just released 2.0.0 which uses API v2. As soon as Maven Central is finished with its "processing time", it will be available.

**Comment by SubJunk** [comment]
Nice work, thanks for letting me know

**Pull request merged**
